--SCRIPT JUST FOR H2 DATABASE: LOCAL SPRING PROFILE

DROP TABLE IF EXISTS TRACKS CASCADE;
CREATE TABLE TRACKS (
	TRACK_ID BIGINT NOT NULL AUTO_INCREMENT,
	ISRC VARCHAR(12) NOT NULL,
	DURATION INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (TRACK_ID)
);
