----SCRIPT JUST FOR H2 DATABASE: For UnitTesting

DROP TABLE IF EXISTS ALBUMS CASCADE;
CREATE TABLE ALBUMS (
	ALBUM_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(45) NOT NULL,
	YEAR INTEGER NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	MODIFICATION_DATE TIMESTAMP NOT NULL,
	PRIMARY KEY (ALBUM_ID)
);

DROP TABLE IF EXISTS TRACKS CASCADE;
CREATE TABLE TRACKS (
	TRACK_ID BIGINT NOT NULL AUTO_INCREMENT,
	ISRC VARCHAR(12) NOT NULL UNIQUE,
	DURATION INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    MODIFICATION_DATE TIMESTAMP NOT NULL,
    ALBUM_ID BIGINT NOT NULL,
    PRIMARY KEY (TRACK_ID),
    CONSTRAINT FK_ALBUM_ID  FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS (ALBUM_ID)
);
